### ISSUE TITLE
Execution failes

### ISSUE THREAD

**Issue by namjul** [sharpcdf/jitter#14]
After running the bash install script I was not able to execute jitter. The following error accurs.

```
jtr: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by jtr)
jtr: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by jtr
```

**Comment by ghost** [comment]
what distro are you on? it may be a dependency that im not aware of

**Comment by ghost** [comment]
try installing glibc with your package manager, on fedora `glibc-devel` exists, and may be required to run it, but im not sure.

**Comment by namjul** [comment]
Running `sudo apt install glibc-source` on ubuntu  made it work. Thank you.
